const blogPages = ["BlogPost1.html", "BlogPost2.html", "BlogPost3.html", "BlogPost4.html", "BlogPost5.html"];

let p1 = document.createElement("p");
let p2 = document.createElement("p");
let p3 = document.createElement("p");
let p4 = document.createElement("p");
let p5 = document.createElement("p");
let p6 = document.createElement("p");
let p7 = document.createElement("p");
let p8 = document.createElement("p");
let p9 = document.createElement("p");
let p10 = document.createElement("p");
let p11 = document.createElement("p");
let p12 = document.createElement("p");

let path = window.location.pathname;
let pageName = path.split("/").pop();

let section = document.getElementById("blog-section");

let heading = document.createElement("h1");


       if(pageName == blogPages[0])
        {
                console.log("on page 1");
                heading.innerText = "Close Reading - Overview of Data Visualisation";
                
                p1.innerText = "This essay will begin by defining what data visualisation is as well as what roles it plays in our everyday lives. Then it will explore the advantages of data visualisations, the role of the viewers who engage with these visualisations as well as how and why certain knowledge is privileged when creating them."
                p2.innerText = "Qi Li, in his essay, ‘Overview of Data Visualisation’ (2020), defines it as “the presentation of data in a pictorial or graphical format” (Li, 2020). Li expands on this statement by emphasising the intuitive and interactive experience data visualisation provides for viewers (Li, 2020). The main goal of traditional data visualisation is to communicate a range of pre-selected information to viewers. Visualising data has several advantages such as the ability to display a large volume of information (defined as processed/meaningful data) to viewers. It also allows viewers to build upon the original data set to either formulate their own future predictions or to identify unforeseen correlations within the data. Another advantage is also how much more accessible data is for the general public, as it incorporates younger audiences and begins to destroy the mental barrier for those who believe only science-minded people can engage with these datasets. However, another side to this is that it encourages an overloading of information e.g., visualisations present much more information than a summary would.  They are also playing a bigger role in popular media, in the sense that with the evolution of social media, analytics are becoming a larger prioritisation for casual users."
                p3.innerText = "Li explains how the data visualisation is split into two major sub classes. The first is information visualisation. Information visualisation is the visual representation of abstract data (Li, 2020). Abstract data is “the reduction of a particular body of data to a simplified representation of the whole” (What is data abstraction in programming and database management?, 2022). This requires the person visualising and/or organising the original data set to select which parts of the data they see as most valuable. Hence introducing a system of validation where certain data is privileged over other data in order to produce a more comprehensible visualisation. In this way the creator’s “ways of knowing”( Rettberg, 2020) are privileged as they get to decide what “kinds of knowledge” (Rettberg, 2020) to enable."
                p4.innerText = "The other subclass of data visualisation is scientific visualisation. Scientific visualisation is described as the representation of what is normally physically based scientific data (Li, 2020). Scientific data is “information which is based on research carried out by scientists and which has been published in a peer-reviewed journal” (Scientific Data Definition | Law Insider, 2022)."
                p5.innerText = "Li goes on to define the differences between data and information as well as provide a deeper examination into the different types of data. Data is defined as “raw, unprocessed information” (Li, 2020) that is not associated with a particular meaning. They are two main types of data, primary and secondary data. Primary data is “collected from the […] individual respondents directly” (Li, 2020) whereas secondary data is data collected from other sources (not done by the researcher) for a purpose that is different from that in which the original data was gathered. Lastly, information is defined as meaningful data."
                p6.innerText = "Data visualisation is considered an interactive activity therefore it is the role of the viewer to perceive the data being displayed to them. Perception is “the process of recognising […], organising […] and interpreting […] sensory information” (Li, 2020). Floridi and Chen in their essay, ‘An analysis of information visualisation’ (2013) describe viewing as “the process of specifying significant or noteworthy information” (2013). This emphasises how great the role of the viewer is when it comes to conveying information, as a visualisation becomes pointless if viewers are not able to engage with it. It is within the viewing process that users can make judgements about how this information will affect their lives e.g. during COVID-19, data visualisations encouraged the use of masks by visualising how affective they were in preventing the spread of the virus. Viewers can also form their own hypothesis based on previously defined data visuals, that is they can use previously made data visuals as secondary data for their own research."  
                p7.innerText = "The heavy reliance on viewers’ ability to engage with the visualisations introduces new inequalities in the form of “access to the kinds of literacies needed for making sense of data visualisations” (Hiippala, 2020). Hiippala describes the term ‘ergodic work’ as the amount of effort required from participants. In the case of data visualisation, ergodic work is directly correlated to exploration. Hippala defines exploration as the “degree of interacticity” provided for users (Hippala, 2020). The more interaction a visualisation contains the more ergodic work is required from the viewer to fully comprehend the displayed data. Some viewers have expressed that if a visualisation takes too much ergodic work, they will avoid interacting with the visualisation, as they see it as work which “does not come easily” (Kennedy, Allen, Engebretsen, Hill, Kirk, Weber, 2021)."
                p8.innerText = "The particular layouts of a space affect how viewers relate to data (Hippala, 2020). Hence why data has a number of different formats it can be organised into such as graphs, charts, tables etc. The notion of space changing how we relate to data is applicable to the physical media in which we display these visualisations. Mobile devices have become the leading device for these types of interactions resulting in the “widespread adoption of mobile first” (Kennedy et al., 2021) this opens doors for new levels of interaction where using your finger to scroll down a page is likely to reveal some sort of technical effect."
                p9.innerText = "When it comes to structures of power, society has given “systemised data” (Rettberg, 2020)  a high level of authority. This can be seen in the way data visualisations have privileged the average to a position where it is not only idealised but seen as the goal. The idealised average comes in opposition to earlier traditions which praised an ideal body, that was encouraged to be worked towards but ultimately was seen as unachievable (Rettberg, 2020). Modern day society has created a place of comfort with the average, as users, we are more concerned with whether something is ‘normal’ and take pride when our statistics are within these bounds of normalcy. However as consumers, we should be aware that normalcy tends to be measured by those with the most power as opposed to those with the greatest knowledge, as a result countries affected by the digital divide tend to have much less of a say than other countries."
                p10.innerText = "In conclusion, this essay has touched upon what data visualisation is as well as its advantages to society. It has highlighted how data visualisation encourages the average person to act and even encourages them to observe the data in a critical manner so that they are able to come to their own hypothesis. It has explained how knowledge barriers affect different interaction rates with visualisations, as overwhelming visualisations require more ergodic work from the user. It explores how visualisations can create a space which supports and encourages interaction but sometimes still does not allow the user to contribute meaningfully to the data. Data visualisation in itself encourages certain ideologies and predefined beliefs whilst suppressing others therefore users should engage with them critically in order to be in control of their own truth."
                
                section.append(heading, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);

        } else if(pageName == blogPages[1])
        {
            console.log("on page 2");
                heading.innerText = " UI/UX Critical Writing Analysis";

                p1.innerText = "Design is the conscious intuitive effort to impose meaningful order” (Papanek, 1984). When designing my User Interface (UI) and User Experience (UX), I aimed to design an environment which evoked positive emotions within the user. This meant avoiding any sort of possible frustrations by communicating clearly to my user where information was located and how to complete each task (Hassenzahl and Tractinsky 2006)."
                p2.innerText = "Hassenzahl and Trackinsky in their paper, ‘User Experience a Research Agenda’ (2006) speak of having emotions as design goals. Even though it cannot be guaranteed that the user will feel joy and/or excitement when they look at my website. I have still made certain design decisions in order to subtly alter how the user feels when engaging with my website. Aiming to alter how a user feels may be considered a dark UX pattern as the designer’s intentions are not being clearly stated to the user (Goldberg, 2022). I chose to go with a lighter/happy theme such as ‘Studio Ghibli’ (1985) because I wanted the user to be drawn in by the visual aesthetic of the website. I also aimed to emulate similar feelings to those that would be evoked when watching the movie, that is feelings having been whisked away to another world. I wanted to captivate users who may not have watched any ‘Studio Ghibli’ (1985) movies or had any experience with the primary data the website is based on to feel as though they wanted to learn more about the studio. UX management speaks to the designers ability to influence how the user behaves (Goldberg, 2022). My website at the moment, lacks any explicit call to action’s (CTA) as it does not have any underlying aim to generate some sort of gain e.g. financial. However, it does attempt to influence the user’s behaviour, by trying to provoke a set of positive emotions when the user interacts with the website." 
                p3.innerText = "Another way, I attempted to produce positive emotions within users is by layering information in a logical structure. I grouped information using a hierarchical layout, with the most important information at the top of the page, that being the navigation bar followed by the heading of the webpage underneath it. I wanted to reflect the idea of conscious effort by purposefully grouping elements such as navigation icons in areas that were instantly visible to the user. I also made sure the current page the user was on was highlighted, and that the navigation bar was static, so as to provide a reference point for the user. I wanted the pages to have a minimalistic look because they contain a lot of bright greens and blues in the background therefore I did not want them to come off as overwhelming. To avoid this I removed individual references and placed them on their own separate page and I also tried to create high contrast between the text and  the background by adding a white background for big buttons. On pages with a lot of text, I removed the background image and included a solid turquoise background instead as shown in the Figure 1 wireframes. I decided to go with a green and blue colour because I liked that they can be considered earthy colours, whilst also being vibrant enough to create a positive environment. I used white to contrast against these colours because I thought a dark background with white text would seem too gloomy. I decided to use the font Coda_Caption because its font weight stood out on the bright Studio Ghibli background, and was quite easy to skim when placed in paragraphs, however a downside to this font is that it is not dyslexia friendly as certain letters when reversed look identical to others."

                let img1 = document.createElement("img");
                img1.src = "../IM_3B/Images/BlogPostTheory2Img/Fig1.png";
                img1.classList.add("img-1");
                img1.alt = "Image of website wireframes";

                let figureText1 = document.createElement("h3");
                figureText1.innerText = "Figure 1. showing website wireframes";

                let img2 = document.createElement("img");
                img2.src = "../IM_3B/Images/BlogPostTheory2Img/Fig2.png";
                img2.classList.add("img-2");
                img2.alt = "Image showing website style guide";

                let figureText2 = document.createElement("h3");
                figureText2.innerText = "Figure 2. showing the styleguide";

                p4.innerText = "The web encourages a predator’s glance, processing a vast amount of fleeting information fast, before focusing on a target” (Blair-Early and Zender, 2008). Another reason why I did not want my pages to look overloaded was because I wanted to make it easy for people skimming my website to get a good idea of what each page was about. For that reason, I created five tabs in my navigation which separated the home page, from the blogs, data, design and references. From there, the blogs, data and design have their own sub sections which the user can select from. I grouped sections in this manner to reduce complexity and the number of decisions a user is faced with in one particular moment as the “[t]ime it takes to decide increase[s] with the number and complexity of choices” (Goldberg, 2022).";
                p5.innerText = "On my blog post pages, I need to work on aligning the buttons with the edges of the paragraph, as the alignment sticks out in a way which is noticeable to users and “good alignment is invisible” (Goldberg, 2022). I would like the ‘previous’ button to be aligned with the left side of the paragraph, the top button in the middle and the ‘next’ button to always be aligned with the right side of the paragraph. I would also like to make sure the references align with the main text. The blog post pages make predominant use of straight edges for alignment as straight lines are seen as being more serious."

                let img3 = document.createElement("img");
                img3.src = "../IM_3B/Images/BlogPostTheory2Img/Fig3.png";
                img3.classList.add("img-3");
                img3.alt = "Image showing misaligned button and reference elements";

                let figureText3 = document.createElement("h3");
                figureText3.innerText = "Figure 3. showing misaligned button elements";

                p6.innerText = "Another change I would like to make is to ensure that my mouse cursor changes appropriately. I want the mouse cursor to clearly communicate the function of the element on which the user is hovering in order to avoid mistakes. Mistakes in this context are conscious errors the user makes when their idea of how the website works is different to how the website actually functions (Goldberg, 2022). I also think that even though my website does provide immediate feedback i.e. when the mouse hovers over a clickable object it turns into a pointer cursor, and the element will change colour, it would be beneficial if there was also a sound effect, that way feedback would be audible and visual. However, I think it may only be beneficial to add sound design to elements of my website in which the user requires the most feedback as feedback should be “minimal” and “proportional to action’s importance” (Blair-Early and Zender, 2008)."
                p7.innerText = "Big improvements I am planning to incorporate on my website is the scrolling effect which can be seen on Apple’s website, which enables an animations to run when the user scrolls through the webpage. I plan to add these animations in, but with small snippets from the Studio Ghibli movie running when the user scrolls. I would also like to allow the user to customise some aspect of the website, whether that be by uploading a profile picture or saving their favourite movie data, however, this would require me to do some more research on the back-end as personalised information would need to be saved on some sort of database.";
                p8.innerText = "In conclusion, this reflection looks at how I planned to create a user experience which provoked certain positive emotions and mistakes I have made which disrupted this experience such as alignment issues. It also looked at future improvements, I plan to implement such as sound design as part of my immediate feedback, customisation as well as mimicking Apple’s scrolling effect which they use throughout their website.";
                section.append(heading, p1, p2, p3, img1, figureText1, img2, figureText2, p4, p5, img3, figureText3, p6, p7, p8);

    } else if(pageName == blogPages[2])
    {
        console.log("on page 3");
        heading.innerText = "Close Reading - Interaction for Data Visualisation";

        p1.innerText = "In this essay I will be analysing the paper, ‘Interaction for Data Visualisation’ (2019) by Evanthia Dimara and Charles Perin. The aim of the paper is to provide a definition for what interaction means in the world of data visualisation. I will discuss how Dimara and Perin gathered data for their study and what aspects of interaction they considered when producing their definition of interaction.";
        p2.innerText = "Dimara and Perin begin the paper by defining their criteria for the data their study will be based on. One of these requirements emphasises the difference between interaction within the context of data visualisation and that of Human Computer Interaction (HCI). Dimara and Perin insist that any mention of interaction within the field of HCI is not valid within their study unless it explicitly speaks about interaction within data visualisation as well. This emphasises the fact that how a user engages with information displayed to them, will depend on what information you as the developer are trying to convey. Hence, designing a user interface for a theory blog webpage requires different design considerations than when condensing data from an API onto a visualisation. Interactions within data visualisations can be more complex than HCI in the sense that the designer is trying to portray a large volume of information in a manner that “strengthen[s the] viewer’s understanding of the underlying data” (Roels, Baeten,and Signer, 2016). The designer encourages viewers to identify trends in the data as “[h]umans have a remarkable pattern recognition system … the ability for knowledge discovery in data-driven science depends critically on our ability to perform effective and flexible visual exploration” (Teras and Raghunathan, 2015).";
        p3.innerText = "Before diving into the definition of interaction, Dimara and Perin begin by identifying key aspects of interaction such as ‘user’ and ‘data’. Dimara et al. expands on the link between user and data by exploring how “[i]nteraction is conceptualised as a dialogue between a human user and the visualisation system over a central object of interest: the data” (Dimara and Perin, 2019). They go on to define the user as “a human being who can be characterised by skills, abilities, expertise and motivation, and who initiates the interaction” (Dimara and Perin, 2019). It is noted the term, ‘user’ does not exclude entities which may be considered to be non-human. Dimara et al. define data as “an intangible information source that is the user’s main object of interest”(Dimara and Perin, 2019). I would argue that the information source itself is not the user’s main interest but rather the trends we pick up whilst analysing the data, that becomes our main focus.";
        p4.innerText = "Dimara et al. propose the scope for what makes up an interaction, this ranges from physical interaction, user interactions, the user’s mental representations as well as internal interactions which take place as thoughts in the user’s mind. Dimara et al. go on to list the properties of interaction such as the fact that it tends to be goal oriented, executed one step at a time in a sequential manner, repeatedly. Interactions can be subdivided into two characters, continuous and discrete. Continuous interactions “involve a sequence of intermediate visualisation states between an initial state and a goal state which happen over a span of time” (Dimara and Perin, 2019). Whereas, discrete interactions “occur in a distinct manner” (Dimara and Perin, 2019).";
        p5.innerText = "Even though the seven categories of Human Computer Interaction are functional within the realm of data visualisation, they are key differences between how interaction is expected to operate within the two contexts. Dimara et al. highlights these differences, starting with entities at play, the HCI review points out that interaction involves “two entities … engaged in an interplay of sorts” (Hornbaek and Oulasvirta, 2017), however in the field of data visualisation, this interaction must involve data. HCI aims to make the interface as simple and intuitive as possible whereas VIS (visualisation) aids the user in manipulating (e.g. filtering) the data in order to identify trends and outliers. VIS works on “providing users more control over the visualisation process in order to enable the interactive exploration and discovery of meaningful relations” (Roels et al., 2016). The goals of the user also differ as with HCI, goals may be formed “outside of the interaction cycle” (Dimara and Perin, 2017). For example, one may want to transfer money to someone, they can decide to use a banking application to do so, but their intention was not formed because they were using the app, rather they are using the app because of their intention. This is opposed to data visualisation where engaging with a visualisation, may persuade one to filter the data in different ways in order to find other corresponding trends, in this case, my engagement is directly affected by the visualisation conveyed to me and the information it is displaying.";
        p6.innerText = "In conclusion, this essay has included a review of Dimara et al.’s demonstration of how interaction differs within the context it is used and how user intent affects the way an interface is developed to encourage interaction. They end their paper by defining interaction for visualisation as “the interplay between a person and a data interface involving a data-related intent, at least one action from the person and an interface reaction that is perceived as such” (Dimara and Perin, 2017). This definition acknowledges that data and the user are key aspects for communication. It also addresses that the system must react in response to the user’s input.";
    
        section.append(heading, p1, p2, p3, p4, p5, p6);
    } else if(pageName == blogPages[3])
    {
        console.log("page 4");
        heading.innerText = "Close Reading - Interaction for Data Visualisation";

        p1.innerText = "My aim with my data art was to portray my perception of the Studio Ghibli dataset. When it comes to data, even if one takes the stance that data is neutral, it is almost impossible to view data visualisation as impartial. This is because the person analysing the data goes through a process of filtering in which they discard data they feel is irrelevant to the story they are trying to convey. The “[d]ata visualisation process is […] designed to engage the viewer in envisioning […] the stories associated with particular information” (Taylor, 2017). The points in my dataset are surrounded with the statistics surrounding individual stories. With my data visualisations, I used these statistics to show the viewer that the films were high ranking, and reasons which I thought may have contributed to their high success rate. However, with my data art, my aim was to display a more visual aesthetic in order to rope the viewer into the individual stories of the actual data points i.e., each movie, as opposed to the trends that are displayed overall.";
        p2.innerText = "I was not sure if the API I chose would work for creating the type of art I wanted to curate with my data. Hence, I am considering creating my own database or seeing if I can find a collection of images from the film. It was important for me to be working off some sort off dataset as for an “artwork to be classified as a visualisation, must be based on actual data” (Taylor, 2017). I would then use those images to create an artwork which would look similar to a collage but also a colour script. Colour scripts are commonly used in animations to convey the tone and pacing of the film. Therefore, I felt it would be fitting, to use photographic data from the films to create an overarching view of the film's visual colouring. This may help users on my site who have not seen some of the films to pick which one they would like to see, as they can filter through the art for happier (brighter coloured) films. In the same way, they can filter for films which seem to be set in nature (green/blue) as opposed to industrial (grey) based films.";
    
        let img1 = document.createElement("img");
        img1.src = "../IM_3B/Images/DataArt/DataArtEx1.jpeg";
        img1.classList.add("img-1");
        img1.alt = "Data Art Example 1";

        let figureText1 = document.createElement("h3");
        figureText1.innerText = "Figure 1.";

        let img2 = document.createElement("img");
        img2.src = "../IM_3B/Images/DataArt/DataArtEx2.png";
        img2.classList.add("img-2");
        img2.alt = "Data Art Example 2";

        let figureText2 = document.createElement("h3");
        figureText2.innerText = "Figure 2.";

        p3.innerText = "In terms of how I would implement the colour script/collage my data art. I have a number of options in mind. One would be to only use the collage of colours in the background and then to create a new dataset containing all of the images of the main characters from each film. I would then combine all of the characters. For the background, I would take the main colour from the cover of the film and then align each colour side by side, add in a smooth transition between colour changes to show the shift in background colours of the movie posters over time. An example of the combined characters without the specialised background can be seen in figure 3.";
    
        let img3 = document.createElement("img");
        img3.src = "../IM_3B/Images/DataArt/SGCharacters.jpeg";
        img3.classList.add("img-1");
        img3.alt = "Data Art Example 3";

        let figureText3 = document.createElement("h3");
        figureText3.innerText = "Figure 3.";

        p4.innerText = "Another idea I had was to create a single movie poster/collage for all of the ‘Studio Ghibli’ movies. As I want my data art to communicate a visual overview for all the movies. This poster would be a collage of all the images in the dataset carefully positioned around the title, ‘Studio Ghibli’. The dataset contains images of all the cover posters from each movie therefore I would just be trying to arrange each image in a way which allowed each individual poster to be seen clearly. I then would also add in an element of interaction, where the user just needs to hover over each image in order to see an expanded version of that movie’s cover image. I also think it would be interesting to add in a filter process which when certain movies were unselected from a list, the collage would reorder itself and resize all of the images to accommodate the changes. This would require an algorithm which would ensure that regardless of which movies where selected, the title could be seen at all times, and that there was no unnecessary background space, as the movie covers would be layered on top of one another filling up the pre-defined grid space.";
        p5.innerText = "My data art was not really designed with the idea of providing a new way of thinking about the data but rather aims to reinforce the ideologies already implemented by the website. The aim of my art is to lure the viewer, and leave them wanting more. Therefore I wanted my data art to be visually striking yet also give the viewer a quick insight into what each movie is about.";
        p6.innerText = "I wanted my data art to enhance the purpose of my website. This meant making the movie franchise come off as appealing as possible. This is why I felt it would be beneficial for my data art to mimic advertisements, in order to lure the viewer into engaging with the Studio’s work in the same way an ordinary movie poster would. I wanted to curate a visual summary of the franchise’s work by using all 22 cover’s for the film, to create one large overview for the film series. Moreover, I wanted to use the affordance that comes with it being digital and manipulated by data to incorporate interaction.";
        p7.innerText = "In terms of improving my data art, I think it would be beneficial to add in an informative interactive component. It would be more intriguing for the viewer if when they hovered over a character, some information which was relative to who they are and what the movie in which they star in is about, could appear, as a “good visualisation […] includes information […] and visual form” (Taylor, 2017). I would also like the background to change depending on what the background of the movie cover is about. As colour does have ability to build certain expectations and bring about connotations on what type of emotions the film is attempting to convey in the viewer. I think interaction would enhance this type of visualisation because it “heavily involves the spectators”(Wong, Jung & Yoon, 2009). It also expands the volume of information the user can extract form the artwork, as they can examine the aspects of the work which drawn their attention.";
    
        section.append(heading, p1, p2, img1, img2, p3, img3, p4, p5, p6, p7);
    } else if(pageName == blogPages[4])
    {
        heading.innerText = "Data Visualisation, Data Art, and Representation";

        p1.innerText = "In this essay, I will discuss how the process of presenting data in any form, requires the curator to filter through big data. How this in turn creates prejudice in the information produced. I will also examine how data is used in the interactive space, and how interaction differs in data art and data visualisation. Lastly, I will investigate the similarities and differences between the modes of representation used in data art and data visualisation.";
        p2.innerText = "Data visualisations and data art both make use of data to evoke some sort of reaction from audiences. As data in itself is raw, un-processed data, it has no prejudice. Raw data is not associated with a specific meaning (Li, 2020). However prejudice does occur when obtaining the data, for example, which regions data is collected from and how. “[D]ata is something that is ‘constructed’” (Manovich, 2015: 18), therefore visualisations and data art take this non-biased data and essentially give it prejudice. When an artist or data scientist put together the data, they are not only trying to make it more “accessible and understandable” (Sadiku, Shadare, Musa and Akujuobi, 2016: 11). They are also trying to convince the user on their stance of what they believing the data is communicating. Data scientists may make use of design principles, such shape, colour and size to differentiate between data points they want the viewer to focus on and data points which they would prefer the viewer not to see (Roels, Barten and Signer, 2016).  ";
        p3.innerText = "The process of visualising data whether it is art or not, involves selecting and filtering data points. In order to turn data into information, a “relational connection” (Li, 2020) is required. This process of eliminating ‘unnecessary’ data points (i.e. points which may be considered anomalies, because they do not coincide with the story being created), produces bias in the information, as certain data is valued over others. As a result, viewers should be aware that data can often be presented in a manner which may be somewhat misleading. The idea that data has no prejudice, is also misleading when used in the context of visualisations, as it ignores all processes of bias the data has undergone to be condensed in a manner which is comprehensible for the general public.";
        p4.innerText = "What differentiates data art from data visualisation is the intention of the creator. “Artistic visualisations are visualisation of data done by artists with the intent of making art” (Viegas and Watterberg, 2007:2). Art differentiates from visualisation as there is no link between the data and the visual presented (Viegas and Watterberg, 2007). Data art tends to confront the issues raised by technology and data, and the control it gives to big corporations and governments (Viegas and Watterberg, 2007). ";
        p5.innerText = "“Data visualisation changes the way people experience information and the ways we live” (Aparcio and Costa, 2014:10). When data is visualised, the patterns and overall trends are highlighted. These trends are then used to curate a story which will appear to an audience. Visualisations encourage the users to look at the way the data is presented and make their own judgements (Dimara and Perin, 2020) as “[s]tories can serve as a source for drawing conclusions” (Roels, Baeten and Signer, 2016: 4). This empowers the user, by giving them their own agency to create their own story. However, it cannot be ignored that data visualisations vary in how they represent the data. Therefore a visualisation which clearly emphasises that e.g. 60% of the population is estimated to get COVID, will provide the viewer with less agency than a visualisation which displays a graph that portrays a visible trend. ";
        p6.innerText= "“[O]ur brain performs better as active explorer[s]” (Roels, Barten and Signer, (2016: 3), hence it can be better for viewers to reach a conclusion on the data by themselves as opposed to being told a statistic. This is true for a number of reasons. First, forcing the viewer to analyse the data themselves, encourages them to sit down and engage with the information in a thorough manner. It also rewards them with the feeling that they figured out the trend, as it was not explicitly pointed out to them. However, if the patterns are too implicit, the viewer may miss the point and instead come up with their own conclusion which may not have been the main story the curator was attempting to convey. However this is also an affordance, as any trend in the data, helps the viewer gain a better overview of what information the data holds.";
        p7.innerText = "Interactive data art “is a form of art that heavily involves the spectators” (Wong, Jung and Yoon, 2009: 180). The spectator is mainly involved in two ways. One, is in the way the art requires physical interaction. As the user can either zoom in or out, or any other method which allows the user to control the way in which they view the data. The art changes in response to the user’s touch. The other way the spectator is involved is in the way, they respond to the data that is being presented to them. This may be in evoking an emotional response in the viewer, or in analysing the data in order to gain their own understanding of it.";
        p8.innerText = "Interactive data visualisations allow the user to manipulate the visualisation. Because the visualisation may result in a more predictable way to interactive data art, it is necessary for the mode of navigation through the visualisation to be as intuitive as possible. Data visualisations tend to include interactions which allow the user to filter through big data, zoom into and out of data points and/or select certain data points in order to gain more information about them. It should also be noted that interaction comes with a cost, having too many “allowable actions” (Dimara and Perin, 2020: 9) increases the complexity of the user interface which strains user experience.";
        p9.innerText = "The way someone interprets any form of data representation, involves their personal experiences. As “[d]ata becomes information in the consciousness of a human subject” (Teras and Raghunathan, 2015: 1012). This means that the context in which one grew up, their beliefs and how they have been exposed to the type of data they are shown previously, will all affect the user’s understanding of the data that is displayed to them. This is one of the reasons why data visualisations tend to focus on telling a single story whereas data art is open for personal interpretation by the viewer. Visualisations tend to communicate a specific point they want the user to understand. However data art, tends to present the data in a more neutral manner, in the sense that instead of imposing one specific meaning over the representation, the artists make use of the data to convey an idea which the user can interpret however, they would prefer.";
        p10.innerText = "'Signs shape our perceptions' (Kidd, 2015: 20), hence the way that viewers see data represented nudge viewers to believe certain trends are true. However, visual data can only guide a user’s understanding, it is up to the user and their past experience to determine how the data presented to them, will be understood and therefore the type of meaning it makes in their lives. As data art encourages, users to critically reflect on what the art is communicating, whereas data visualisations tend to more explicitly call the viewer to action in order to defeat certain trends e.g. COVID increases.";
        p11.innerText = "“We should all be encouraged to think about how our own contexts, ideas, prejudices and inevitably partial world-views filter into and frame the representations we construct, shaping the codes and conventions that we utilise in order to construct meaning therein” (Kidd, 2015: 22). We should also be encouraged to be wary of the way world views affect the way in which the creators of data art and visualisation present their data to viewers. When looking at a visualisation, it is important to contextualise information and consider any possible biases which could have influenced the way the data is present. The act of representing something already implies “the active work of selecting and presenting, of structuring and shaping” (Kidd, 2015: 22). Therefore, it is important to question why and how the data was shaped in the construction of the presented information. Representations not only affect how we view a piece of data visualisation or data art, but rather affects how we understand that data in the context of the world around us, thus influencing our future actions in relation to the represented topic (Kidd, 2015).";
        p12.innerText = "In conclusion, I explored how data in itself may be viewed as non-biased, but how information is biased as the result of how the data is converted into information. I also examined the effects of the perception of information and how this relates to the context the user brings with them when studying any piece of data. I looked at the differences between data art and data visualisation, from the perspective of the user as well as the perspective of the creator. Lastly, I spoke about the bias the user brings when examining data, and how their bias is connected to their own context.";
    
        section.append(heading, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }


